#!/usr/bin/env python3

import re
from dataclasses import dataclass
from ipaddress import IPv4Interface
from os import environ

import netifaces
from jinja2 import Template

REGEX_IB = re.compile('^en(P2|)p[12]s0f[01]np[01]$')
HOME = environ['HOME']
MOD_NAME = environ['MOD_NAME']
MOD_DESCRIPTION = environ['MOD_DESCRIPTION']
MOD_MAINTAINER = environ['MOD_MAINTAINER']

TEMPLATE_HEADER = """#
# This file was generated by a Sparkrun mod -- Manual edits will be reverted the next time it runs!
#
# {{ MOD_NAME }} -- {{ MOD_MAINTAINER }}
# {{ MOD_DESCRIPTION }}
#
"""

@dataclass()
class IBInterface:
    name: str
    interface: IPv4Interface

    @property
    def ip(self):
        return self.interface.ip

    @property
    def netmask(self):
        return self.interface.netmask

    @property
    def network(self):
        return self.interface.network

    @property
    def roce(self):
        # enp1s0f1np1, enP2p1s0f1np1
        # rocep1s0f1, roceP2p1s0f1
        return re.sub(r'np[01]$', '', re.sub(r'^en', 'roce', self.name))

ib_interfaces = []
nfsd_ip = None

for name in netifaces.interfaces():
    match name:
        case _ if (m := REGEX_IB.match(name)):
            try:
                ip = netifaces.ifaddresses(name)[netifaces.AF_INET][0]['addr']
                mask = netifaces.ifaddresses(name)[netifaces.AF_INET][0]['netmask']
                interface = IPv4Interface(f"{ip}/{mask}")
            except KeyError as e:
                continue
            ib_interfaces.append(IBInterface(name=name, interface=interface))
            print(f"Found CX7 device: {name} ({interface})")
            continue
        case _:
            continue

# Create .env.roce
template_env_roce = Template(
"""{TEMPLATE_HEADER}
NCCL_SOCKET_IFNAME: {{ ib_interfaces[0].name }}
GLOO_SOCKET_IFNAME: {{ ib_interfaces[0].name }}
NCCL_IB_HCA: {{ ib_interfaces | map(attribute='roce') | join(',') }}
NCCL_IB_DISABLE: '0'
NCCL_IB_ROCE_VERSION_NUM: '2'
NCCL_IB_GID_INDEX: '3'
NCCL_NET: IB
NCCL_NET_PLUGIN: none
NCCL_NVLS_ENABLE: '0'
NCCL_CUMEM_ENABLE: '0'
NCCL_CROSS_NIC: '0'

""", trim_blocks=True, lstrip_blocks=True)
print("Writing .env.roce")
with open(".env.roce", "wt") as env_roce:
    env_roce.write(template_env_roce.render(ib_interfaces=ib_interfaces))
